### ISSUE TITLE
General appearance - Suggestions (low priority)

### ISSUE THREAD

**Issue by mheinzinger** [sacdallago/embed.predictprotein.org#11]
Here just some things that came to my mind regarding displaying items (absolutely no must to implement now; rather low on the priority list, I guess; can all be discussed on Friday):
- The field "Your Sequence" is currently way too dominant for its importance (maybe swap 3D structure and the "Your sequence field" so that people first see 3D and only last the sequence they've entered).
- The field "Valid sequence passed." is currently also taking too much space in my eyes. Maybe you can just change the background color of the input field where the AA is entered so that the background turns green if valid and red otherwise?
- Instead of having an own tab for "Help" below GO/Subcell, you could add a "?" in each tab that either gives help once a user hovers over or opens a new help site when you click on it?
- Maybe also add a small "?" (help-box) to the "Residue-level features" box which explains how to zoom in (left-click drag&drop) and zoom-out (right click)

**Comment by t03i** [comment]
This is mostly addressed apart from 

> Maybe also add a small "?" (help-box) to the "Residue-level features" box which explains how to zoom in (left-click drag&drop) and zoom-out (right click)
