### ISSUE TITLE
Feature Request: add pLDDT/PAE

### ISSUE THREAD

**Issue by mheinzinger** [sacdallago/embed.predictprotein.org#26]
It would be super useful if users could get a lane in the feature-viewer that shows the pLDDT.
This way it gets immediately obvious which regions of the 3D structure to trust.
Optimally, we also offer coloring according to pLDDT.

In a second step (slightly less important but def. a cool feature to have): visualization of the PAE. This gives additional information on domain packing.

**Comment by sacdallago** [comment]
Interestingly the pLDDT info should already be encoded in the PDB file if I remember correctly, and the viewer should display pLDDT by default if in the PDB file... somehow: it doesn't. Not sure I'll be able to debug this by week end

**Comment by mheinzinger** [comment]
Yup, pLDDT should be absolutely already in the PDB file (in the B-factor column).
So if easy to add: absolutely great feature to have.
PAE can be added later;
