### ISSUE TITLE
Feature Request: add sharable links

### ISSUE THREAD

**Issue by mheinzinger** [sacdallago/embed.predictprotein.org#27]
It would be great to have a feature that allows users to share their results in a single link.

**Comment by sacdallago** [comment]
You can load links now, sharing is in progress

**Comment by t03i** [comment]
This feature was requested another time. So I will work on it with some priority.

Unfortunately, the only way to achieve this nicely (IMO) is to use a backend DB which stores an input to shorthand mapping. For protein name or Uniprot ID, this irrelevant as the ID is already nice, but for fasta or sequence this needs some work.

**Comment by sacdallago** [comment]
Honestly, I thought the the previous solution was good enough and it enabled very easy jumpstarting of a new query, i.e. yyy.zzz.kkk/#/WHATEVER

Where `WHATEVER` is then evaluated to be either a UniProt ID or an AA sequence.

Yes. The links can get as long as len(yyy.zzkk)+2k , but much less engineering needed (no database, no backend, no moving, potentially breaking parts).
