### ISSUE TITLE
Visualization: give user information on 3D prediction progress

### ISSUE THREAD

**Issue by mheinzinger** [sacdallago/embed.predictprotein.org#30]
Currently, the page is (at least on my screen) relatively empty on the left and on the right.
What we could think about is moving the "Predicted Features" panel somewhere outside the current page flow, e.g., towards the left, and show it always (even when scrolling to the very bottom). This enables users to jump with one click from one panel to the other.
It would also give us some panel/space that is always visible to include information on the status of structure prediction (red=failed due to length; orange=in_progress; green=finished).
[visu_suggestion.pdf](https://github.com/sacdallago/embed.predictprotein.org/files/9188241/visu_suggestion.pdf)

**Comment by sacdallago** [comment]
moving the menu is a bit of a major rework of the code and I wouldn't dare to start that now, but I added more clearly what the structure component is doing via colors in the relevant section and interactive page

**Comment by t03i** [comment]
This will only work for large screens. From a page flow perspective, it is more logical to me if the features are above, like in the interactive page.
