### ISSUE TITLE
Cross-reference known sequence variants 

### ISSUE THREAD

**Issue by t03i** [sacdallago/embed.predictprotein.org#53]
If we have a known Uniprot Sequence we could cross-reference known sequence variants. 

If we go for that, we could also query the Uniprot API in general and add relevant information.
However, I am not sure if this is the way to go as it could potentially blur the edges between prediction and experimental data.
What do you guys think? @C-Marquet @sacdallago

**Comment by sacdallago** [comment]
This is specifically a prediction server, if someone inputs a uniprot ID, they get a link to uniprot where they can check out all they care that's on uniprot:

<img width="741" alt="image" src="https://user-images.githubusercontent.com/6240943/189113416-be6f36a7-1d83-40fb-a5a2-f86361915791.png">

I think it's overkill

**Comment by t03i** [comment]
Alrighty! We will leave it at that for now, then.
