### ISSUE TITLE
Favicons and page title

### ISSUE THREAD

**Issue by sacdallago** [sacdallago/embed.predictprotein.org#6]
<img width="213" alt="image" src="https://user-images.githubusercontent.com/6240943/173528937-75ecdf90-85ad-42de-9c99-325c0118e296.png">

- I'd remove all default react favicons :P I don't have a good one to swap it out with, but I rather have none than the react one 😛 
- I'd change the title of the page to `PredictProtein Embed`

**Comment by tihanikolova** [comment]
<img width="265" alt="Bildschirmfoto 2022-06-20 um 19 20 18" src="https://user-images.githubusercontent.com/74813699/174651983-40ddc510-64a7-427b-a7b1-d5995f65b1b4.png">
so..?
